### ISSUE TITLE
B 站cookie

### ISSUE THREAD

**Issue by smallwhitedesu1** [alley-rs/lsar#86]
B 站d的cookie要怎么填 一直提示账号没登录....格式是什么样的...

**Comment by Eyion** [comment]
视频号和腾讯会议能够解析出来吗

**Comment by smallwhitedesu1** [comment]
> 视频号和腾讯会议能够解析出来吗

不清楚

**Comment by thep0y** [comment]
打开B站，登录账号，按下 F12，刷新页面，根据图片里的内容就能找到 cookie 了。

![图片](https://github.com/user-attachments/assets/162719fa-8232-4058-888f-714490ac9d04)
